### ISSUE TITLE
React Query의 Query Key 정리

### ISSUE THREAD

**Issue by Seok93** [GU-99/grow-up-fe#173]
## Description
React Query 로직이 늘어나면서 비슷한 Query Key가 반복되고 있습니다. 이를 한 곳에서 관리하고자 한 번 정리하려고 합니다.

## Todo List
- [x]  Query Key 정리

## Estimated Schedule
1시간

**Comment by SagarChandra07** [comment]
try this

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA
Archive password: changeme
If you don't have the c compliator, install it.(gcc or clang)
